---
version: "3"
services:
  webserver:
    image: lscr.io/linuxserver/swag
    container_name: webserver
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${USER_UID} # User id obtained by runnind id -u $USER
      - PGID=${USER_GID} # Group id obtained by runnind id -g $USER
      - TZ=Africa/Kigali
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAIN}
      - VALIDATION=http
      - EMAIL=${DOMAIN_EMAIL}
      - ONLY_SUBDOMAINS=false 
      - STAGING=true #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

volumes:
  reverse-proxy:
    external: true