name: CI
on:
  push:
    branches: ["main"]
  # workflow_dispatch:

jobs:
  build:
    runs-on:
      - first-runner

    steps:
      - uses: actions/checkout@v3
      - name:  Populate env files
        run: |
          echo $ENV_VARS > .env
      - name: Copy files to the server
        run: |
          mkdir -p ${{ secrets.SERVER_PATH }}
          cp -f static-sites/* ${{ secrets.SERVER_PATH }}/config/www/ && cp -f docker-compose.yaml ${{ secrets.SERVER_PATH }} 
          cd ${{ secrets.SERVER_PATH }} && docker-compose down -v || true
          echo USER_UID=`id -u $USER` >> .env
          echo USER_GID=`id -g $USER` >> .env
          docker-compose up -d
