name: CI
on:
  # push:
    # branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - first-runner

    steps:
      - uses: actions/checkout@v3
      - name: Copy files to the server
        run: |
          mkdir -p ${{ secrets.SERVER_PATH }}
          cp -rf swag/* ${{ secrets.SERVER_PATH }}/config/
          cp -f docker-compose.yaml ${{ secrets.SERVER_PATH }}
          docker network ls | grep reverse-proxy > /dev/null || docker network create --driver bridge reverse-proxy
          cd ${{ secrets.SERVER_PATH }} && docker-compose down -v
          echo ${{ secrets.ENV_VARS }} > .env
          echo USER_UID=`id -u $USER` >> .env
          echo USER_GID=`id -g $USER` >> .env
          docker-compose up -d
