name: CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - first-runner

    steps:
      - uses: actions/checkout@v3
      - name: Copy readme file
        run: |
          mkdir -p ${{ secrets.SERVER_PATH }}
          cp README.md ${{ secrets.SERVER_PATH }}
