name: CI
on:
  push:
    branches: ["main"]
  # workflow_dispatch:

jobs:
  build:
    runs-on:
      - first-runner

    steps:
      - uses: actions/checkout@v3
      - name: Copy readme file
        run: |
          mkdir -p ${{ secrets.SERVER_PATH }} && cd ${{ secrets.SERVER_PATH }}
          cp -r -f data . && cp -f docker-compose.yaml init-letsencrypt . 
